name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pull the New Commit
        uses: actions/checkout@v4.1.7

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Clone ALE Psych
        run: |
          git clone https://github.com/ALE-Psych-Crew/ALE-Psych
          cd ALE-Psych
          git checkout main

      - name: Install haxelibs
        working-directory: ALE-Psych
        run: |
          haxelib --global git hmm https://github.com/ALE-Psych-Crew/hmm
          haxelib --global run hmm setup
          haxelib --global run hmm install

      - name: Generate XML
        working-directory: ALE-Psych
        run: |
          haxelib --global install dox
          haxe docsGenerator.hxml

      - name: Generate Pages
        run: |
          haxelib run dox -i ALE-Psych/docs.xml -o pages
        