name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pull the New Commit
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install haxelibs
        working-directory: ALE-Psych
        run: |
          haxelib --global git hmm https://github.com/ALE-Psych-Crew/hmm
          haxelib --global run hmm setup
          haxelib --global run hmm install
          haxelib --global install dox

      - name: Generate XML and Pages
        run: |
          generateXML.bat
          generatePages.bat

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4