name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pull the New Commit
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Clone ALE Psych
        run: |
          git clone https://github.com/ALE-Psych-Crew/ALE-Psych
          cd ALE-Psych
          git checkout main

      - name: Install haxelibs
        working-directory: ALE-Psych
        run: |
          haxelib --global git hmm https://github.com/ALE-Psych-Crew/hmm
          haxelib --global run hmm setup
          haxelib --global run hmm install
          haxelib --global install dox
          haxelib install dox

      - name: Generate XML
        working-directory: ALE-Psych
        run: |
          haxelib run lime display windows | Out-File -Encoding ascii docsGenerator.hxml
          Add-Content docsGenerator.hxml "-xml docs.xml"
          haxe docsGenerator.hxml

      - name: Generate Pages
        run: |
          haxelib run dox -i ALE-Psych/docs.xml -o docs -theme themes/ale-psych --title "ALE Psych API" -D themeColor 0xB986FF -D textColor 0xF4F7FF -D website https://github.com/ALE-Psych-Crew/ALE-Psych -D description "API documentation for ALE Psych." -D source-path https://github.com/ALE-Psych-Crew/ALE-Psych/blob/main/source/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
